### ISSUE TITLE
[Frontend] -> Componente de Filtro de productos y/o categorias

### ISSUE THREAD

**Issue by jeff-js** [omarefg/product-collector#27]
Crear componente de filtros:

- Ubicación
- Tiempo
- Categoria

_Validar con **Backend** si se puede implementar algún otro filtro_

![image](https://user-images.githubusercontent.com/5813240/75812666-99630800-5d5c-11ea-9fe3-5531927c86c6.png)

**Comment by wilson-romero** [comment]
Se actualizó en Frontend
