### ISSUE TITLE
[Frontend] -> Implementar Grafico 

### ISSUE THREAD

**Issue by jeff-js** [omarefg/product-collector#28]
## Implementar grafico de Rechart

Teniendo en cuenta los datos mock que se encuentran en el folder del proyecto de **_frontend_**

![image](https://user-images.githubusercontent.com/5813240/75812866-f65ebe00-5d5c-11ea-8368-5cf1401a10d7.png)

**Comment by wilson-romero** [comment]
Se actualizó en Frontend
